SWA: null
callbacks:
  name: null
checkpoint_dir: /allen/aics/assay-dev/users/Dewen/project/baseline_models/
dist_backend: ddp
epochs: 400
gpus: -1
learning_rate: 0.0005
loader:
  NumWorkers: 2
  PatchPerBuffer: 80
  Transforms: [RR,  RF]
  batch_size: 2
  datafolder: //allen/aics/assay-dev/users/Benji/h2b_undersegmentation_fix/curriculum_training/round3
  epoch_shuffle: null
  name: default
loss:
  ignore_index: null
  loss_weight: [1,1,1]
  name: Aux
model:
  name: unet_xy_zoom_0pad_dropout
  nchannel: 1
  nclass: [2,2,2]
  size_in: [65, 384, 384]
  size_out: [65, 384, 384]
  zoom_ratio: 3
precision: 16
resume: null
save_every_n_epoch: 50
scheduler:
  gamma: 0.942
  name: ExponentialLR
  verbose: true
tensorboard: /allen/aics/assay-dev/users/Dewen/project/lightning_logs
validation:
  OutputCh: [0,1,1,1,2,1]
  leaveout: [0.08]
  metric: default
  validate_every_n_epoch: 10
weight_decay: 0.005