##########################################################################################################
# model settings
##########################################################################################################
model: 
  name: unet_xy_zoom_0pad_dropout
  zoom_ratio: 3
  nchannel: 1
  nclass: [2,2,2]
  size_in: [65, 384, 384] 
  size_out: [65, 384, 384]
# path to the trained model
model_path: '/allen/aics/assay-dev/users/Dewen/project/baseline_models/run_4/checkpoint_epoch=239.ckpt'

##########################################################################################################
# Data Info
##########################################################################################################
InputCh: [0]
OutputCh: [0, 1, 1, 1, 2, 1]
OutputDir: '/allen/aics/assay-dev/users/Dewen/project/test_data/new_domain_2/outputs'
# the ratio to resize the image
ResizeRatio: [1.0, 1.0, 1.0]
# the method to normalize your data
Normalization: 10
# the threshold to be applied on your data
Threshold: 0.5 #0.5 # 0.3
# whether to use run time augmentation (may improve the accuracy, but takes much longer to run)
RuntimeAug: False
batch_size: 1
NumWorkers: 1
gpus: 1

##########################################################################################################
# Execution mode: all files of specific type within a directory
##########################################################################################################
mode:
  name: folder
  # paths to the file
  InputDir: '/allen/aics/assay-dev/users/Dewen/project/test_data/new_domain_2/images'
  # the type of images to be processed in this folder
  DataType: .tiff

validation:
  metric: default
  leaveout: [0.02]
  OutputCh: [0, 1, 1, 1, 2, 1]
  validate_every_n_epoch: 10



