model: 
  name: resnet3d_18_classification
  nchannel: 3
  nclass: 2
  size_in: [40, 256, 256] 
checkpoint_dir: '/allen/aics/assay-dev/users/Dewen/project/experiment_results/all_runs'

# resume: '/allen/aics/assay-dev/users/Dewen/project/baseline_models/run_2/checkpoint_epoch=99.ckpt'
learning_rate: 0.00001 

scheduler:
  name: ExponentialLR
  gamma: 0.91
  verbose: True

weight_decay: 0.005
epochs: 200
save_every_n_epoch: 20
loss:
  name: CrossEntropy # MaskedCrossEntropy
  # name: MultiAuxillaryUncertaintyCrossEntropy
  loss_weight: [1, 1, 1]
  # ignore_index: null
tensorboard: '/allen/aics/assay-dev/users/Dewen/project/experiment_results/logs'
gpus: 1
# dist_backend:  ddp 
precision: 16

loader:
  name: default
  datafolder: '/allen/aics/assay-dev/users/Dewen/project/experiment_results/all_runs/run_22/validation_results'
  batch_size: 8
  PatchPerBuffer: 80
  epoch_shuffle: 201
  NumWorkers: 1
  Transforms: ['RR', 'RF']
  threshold: 0.7
  # uncertainty_type can be: maximum_softmax, entropy, mutual_information, variance
  uncertainty_type: entropy

validation:
  metric: default
  leaveout: [0.1]
  OutputCh: [0, 1, 1, 1, 2, 1]
  validate_every_n_epoch: 20

