##########################################################################################################
# model settings
##########################################################################################################
model: 
  name: resnet3d_18
  nchannel: 3
  nclass: 1
  size_in: [65, 384, 384] 
# path to the trained model
model_path: '/allen/aics/assay-dev/users/Dewen/project/experiment_results/all_runs/run_26/checkpoint_epoch=199.ckpt'

##########################################################################################################
# Data Info
##########################################################################################################
InputCh: [0]
OutputCh: [0, 1, 1, 1, 2, 1]
OutputDir: '/allen/aics/assay-dev/users/Dewen/project/test_data/test/outputs/'
# the ratio to resize the image
ResizeRatio: [1.0, 1.0, 1.0]
# the method to normalize your data
Normalization: 22
# the threshold to be applied on your data
Threshold: 0.7
# whether to use run time augmentation (may improve the accuracy, but takes much longer to run)
RuntimeAug: False
batch_size: 1
NumWorkers: 1
gpus: 1

##########################################################################################################
# Execution mode: all files of specific type within a directory
##########################################################################################################
mode:
  name: cv
  # paths to the file
  InputDir: '/allen/aics/assay-dev/users/Dewen/project/experiment_results/all_runs/run_12/validation_results'
  # the type of images to be processed in this folder
  DataType: .tif

validation:
  metric: default
  leaveout: [0.1]
  OutputCh: [0, 1, 1, 1, 2, 1]
  validate_every_n_epoch: 10

# uncertainty_type can be: maximum_softmax, entropy, mutual_information, variance
uncertainty_type: variance
