##########################################################################################################
# model settings
##########################################################################################################
model: 
  name: BasicUNet
  # number of input channels to the model
  in_channels: 1
  # number of output channels/ classes
  out_channels: 2
  # input patch size given to the network (adapt to fit in your GPU memory, generally bigger patches are better)
  patch_size: [26, 210, 210] #[52, 420, 420]
  #number of dimensions of patch size
  dimensions: 3

# path to the trained model
model_path: '//allen/aics/assay-dev/users/Benji/model_checkpoints/checkpoint_epoch=4-v1.ckpt'
# the channel to extract from output tensors
OutputCh: 1

##########################################################################################################
# Data Info
##########################################################################################################
# the path to output folder
OutputDir: '/allen/aics/assay-dev/users/Benji/mlsegmenter_output'
# the index of the input channel
InputCh: [1] # 1
# the ratio to resize the image
ResizeRatio: [1.0, 1.0, 1.0]
# the method to normalize your data
Normalization: 13
# the threshold to be applied on your data
Threshold: -1 #0.5 # 0.3
# whether to use run time augmentation (may improve the accuracy, but takes much longer to run)
RuntimeAug: False
#adjust this to fit your GPU
batch_size: 8

##########################################################################################################
# Execution mode: all files of specific type within a directory
##########################################################################################################
mode:
  name: folder
  # paths to the file
  InputDir: '/allen/aics/assay-dev/users/Jianxu/data/training_assay_caax_cellmask/quick_test_caax'
  # the type of images to be processed in this folder
  DataType: .tiff #1869_100X_20180327_2r-Scene-14-P47-F04.ome.tiff