##########################################################################################################
# model settings
##########################################################################################################
model: 
  name: BasicUNet
# path to the trained model
model_path: '/allen/aics/assay-dev/users/Benji/model_checkpoints/checkpoint_epoch=206.ckpt'
# number of input channels to the model
nchannel: 1
# number of output channels
nclass: 2
# the channel to extract from output tensors
OutputCh: 1
# input patch size given to the network (adapt to fit in your GPU memory, generally bigger patches are better)
size_in: [26, 210, 210] #[52, 420, 420]
# prediction patch size from the network (change according to input size)
size_out: [26, 210, 210] #[20, 152, 152]

##########################################################################################################
# Data Info
##########################################################################################################
# the path to output folder
OutputDir: '/allen/aics/assay-dev/users/Benji/mlsegmenter_output'
# the index of the input channel
InputCh: [-1]
# the ratio to resize the image
ResizeRatio: [1.0,1.0,1.0]
# the method to normalize your data
Normalization: 10
# the threshold to be applied on your data
Threshold: 0.5
# whether to use run time augmentation (may improve the accuracy, but takes much longer to run)
RuntimeAug: False

##########################################################################################################
# Execution mode: single file
##########################################################################################################
mode:
  name: file
  # paths to the file
  InputFile: '//allen/aics/assay-dev/users/Jianxu/data/training_assay_caax_cellmask/quick_test_caax/3500001803_100X_20180312_3-Scene-14-P24-E06.ome.tiff'
  # is this file a timelapse image
  timelapse: False
  
  
  