model: 
  name: unet_xy_zoom_0pad
  zoom_ratio: 3
  nchannel: 1
  nclass: [2,2,2]
  size_in: [65, 384, 384] 
  size_out: [65, 384, 384]

checkpoint_dir: 'path/to/save/checkpoints/'

resume: "path/to/previous/checkpoints/file.ckpt"
learning_rate: 0.00001 

scheduler:
  name: ExponentialLR
  gamma: 0.91
  verbose: True

weight_decay: 0.005
epochs: 400
save_every_n_epoch: 2
loss:
  name: Aux
  loss_weight: [1, 1, 1]
  ignore_index: null
tensorboard: '/path/to/lightning_logs'
gpus: -1 
dist_backend:  ddp 
precision: 16

loader:
  name: default
  datafolder: [/path/1/, /path/2/]
  batch_size: 2
  PatchPerBuffer: 360
  epoch_shuffle: 10
  NumWorkers: 6
  Transforms: ['RR', 'RF', 'RN']

validation:
  metric: default
  leaveout: [0.02]
  OutputCh: [0, 1, 1, 1, 2, 1]
  validate_every_n_epoch: 1
